In [ ]:
import pandas as pd

## Creating Chunks 1 to 5 from 1st CSV file

In [ ]:
df = pd.read_csv('/content/6M-0K-99K.users.dataset.public.csv')

In [ ]:
df.head()

,identifierHash,type,country,language,socialNbFollowers,socialNbFollows,socialProductsLiked,productsListed,productsSold,productsPassRate,...,civilityTitle,hasAnyApp,hasAndroidApp,hasIosApp,hasProfilePicture,daysSinceLastLogin,seniority,seniorityAsMonths,seniorityAsYears,countryCode
0,-7279641312655250028,user,Etats-Unis,en,3,8,0,0,0,0.0,...,mrs,False,False,False,True,709,3205,106.83,8.9,us
1,-1456013578740053406,user,Allemagne,de,3,8,0,0,0,0.0,...,mrs,False,False,False,True,709,3205,106.83,8.9,de
2,9006282053848196165,user,Suède,en,3,8,0,0,0,0.0,...,mr,True,False,True,True,689,3205,106.83,8.9,se
3,-7154634866120535654,user,Turquie,en,3,8,0,0,0,0.0,...,mrs,False,False,False,True,709,3205,106.83,8.9,tr
4,2858299215060733023,user,France,en,3,8,0,0,0,0.0,...,mr,True,False,True,True,709,3205,106.83,8.9,fr

In [ ]:
df.count()

identifierHash         98913
type                   98913
country                98913
language               98913
socialNbFollowers      98913
socialNbFollows        98913
socialProductsLiked    98913
productsListed         98913
productsSold           98913
productsPassRate       98913
productsWished         98913
productsBought         98913
gender                 98913
civilityGenderId       98913
civilityTitle          98913
hasAnyApp              98913
hasAndroidApp          98913
hasIosApp              98913
hasProfilePicture      98913
daysSinceLastLogin     98913
seniority              98913
seniorityAsMonths      98913
seniorityAsYears       98913
countryCode            98913
dtype: int64

In [ ]:
len(df)

98913

In [ ]:
chunk_size = len(df) // 5 + (1 if len(df) % 5 else 0)


for i in range(5):
  start = i * chunk_size
  end = start + chunk_size
  chunk_df = df.iloc[start:end]
  chunk_df.to_csv(f'/content/chunk_data1/chunk_{i+1}.csv', index=False)

# Creating Chunks 6 to 10 from 2nd CSV file

In [ ]:
df1 = pd.read_csv('/content/users.6M0xxK.2024.public.csv')

In [ ]:
df1.head()

,identifierHash,type,countryCode,country,language,socialNbFollowers,socialNbFollows,socialProductsLiked,productsListed,productsSold,...,productsWished,productsBought,gender,civilityGenderId,civilityTitle,hasProfilePicture,seniority,seniorityAsMonths,seniorityAsYears,websiteLongevity
0,1920991140,user,us,Etats-Unis,en,3,8,0,0,0,...,0,0,M,1,mr,True,3206,106.87,8.91,3803
1,1920860068,user,se,Suède,en,3,8,1,0,0,...,0,0,M,1,mr,True,3206,106.87,8.91,3803
2,1920401316,user,it,Italie,fr,3,8,0,0,0,...,0,0,M,1,mr,True,3206,106.87,8.91,3803
3,1919811492,user,dk,Danemark,en,75,10,1968,0,0,...,43,15,M,1,mr,True,3206,106.87,8.91,3803
4,1919025060,user,de,Allemagne,de,3,8,0,0,0,...,0,0,M,1,mr,True,3206,106.87,8.91,3803

In [ ]:
df1.count()

identifierHash         20743
type                   20743
countryCode            20710
country                20743
language               20743
socialNbFollowers      20743
socialNbFollows        20743
socialProductsLiked    20743
productsListed         20743
productsSold           20743
productsPassRate       20743
productsWished         20743
productsBought         20743
gender                 20743
civilityGenderId       20743
civilityTitle          20743
hasProfilePicture      20743
seniority              20743
seniorityAsMonths      20743
seniorityAsYears       20743
websiteLongevity       20743
dtype: int64

In [ ]:
len(df1)

20743

In [ ]:
chunk_size1 = len(df1) // 5 + (1 if len(df1) % 5 else 0)


for i in range(5):
  start = i * chunk_size1
  end = start + chunk_size1
  chunk_df1 = df1.iloc[start:end]
  chunk_df1.to_csv(f'/content/chunk_data1/chunk_{i+5+1}.csv', index=False)